trigger:
  branches:
    include: 
    - master

pr:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    dotnet publish -c release -o $(build.artifactStagingDirectory)
  displayName: Publish application

- task: PublishBuildArtifacts@1