trigger:
  batch: true
  branches:
    include: 
    - master
  paths:
    include:
    - src/demo-aspnetcore-mvc/*

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    cd src/demo-aspnetcore-mvc
    dotnet publish -c release -o $(build.artifactStagingDirectory)
    cp -R charts $(build.artifactStagingDirectory)
  displayName: Publish application

- task: PublishBuildArtifacts@1