trigger:
  batch: true
  branches:
    include: 
    - master
  paths:
    include:
    - src/demo-aspnetcore-mvc/*

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: Docker@1
  displayName: 'Build an image'
  inputs:
    azureSubscriptionEndpoint: 'MTC Denver Sandbox (b0e04a4a-a321-4b66-b8fd-13715262ba3c)'
    azureContainerRegistry: mtcdensandboxdemo.azurecr.io
    dockerFile: 'src/demo-aspnetcore-mvc/Dockerfile'

- task: Docker@1
  displayName: 'Push an image'
  inputs:
    azureSubscriptionEndpoint: 'MTC Denver Sandbox (b0e04a4a-a321-4b66-b8fd-13715262ba3c)'
    azureContainerRegistry: mtcdensandboxdemo.azurecr.io
    command: 'Push an image'